### ISSUE TITLE
build issues with docker

### ISSUE THREAD

**Issue by tscholak** [stites/pytorch-world#7]
Hi @stites!
Thanks again for putting all this together!
I just ran into some build problems with libtorch on docker. In particular, I ran:
```
$ docker run -it \
  --name nixos \
  nixos/nix:latest
# mkdir -p ~/.config/nixpkgs
# echo "{ allowUnsupportedSystem = true; }" > ~/.config/nixpkgs/config.nix
# nix-build -E 'with import <nixpkgs> {}; let src = fetchFromGitHub { owner = "stites"; repo = "pytorch-world"; rev = "4c4bd205e47477c723209f3677bddceabb614237"; sha256 = "1zqhm0874gfs1qp3glc1i1dswlrksby1wf9dr4pclkabs0smbqxc"; }; in (import "${src}/release.nix" { }).libtorch'
```
and
```
$ nvidia-docker run -it \
  --name nixos-cuda \
  nixos/nix:latest
# mkdir -p ~/.config/nixpkgs
# echo "{ allowUnsupportedSystem = true; allowUnfree = true; }" > ~/.config/nixpkgs/config.nix
# nix-build -E 'with import <nixpkgs> {}; let src = fetchFromGitHub { owner = "stites"; repo = "pytorch-world"; rev = "4c4bd205e47477c723209f3677bddceabb614237"; sha256 = "1zqhm0874gfs1qp3glc1i1dswlrksby1wf9dr4pclkabs0smbqxc"; }; in (import "${src}/release.nix" { }).libtorch-cuda'
```
Both of these fail after a (long) while with:
```
Running test_c10d ... [2019-08-31 18:15:52.593858]
.ss....sssssssssssss.FFsssssssFsss....s..s.s..sF.s..s..s..s..s..s.s..s..s.FsssssssEEEEEEEs........Es
======================================================================
ERROR: test_forward_backward_multi_replica (__main__.ReducerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_c10d.py", line 2783, in setUp
    self.process_group = c10d.ProcessGroupGloo(self.store, 0, 1)
RuntimeError: [enforce fail at ../third_party/gloo/gloo/transport/tcp/device.cc:127] rp != nullptr. Unable to find address for: 2e3c6f147588

======================================================================
ERROR: test_forward_backward_optimizer (__main__.ReducerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_c10d.py", line 2783, in setUp
    self.process_group = c10d.ProcessGroupGloo(self.store, 0, 1)
RuntimeError: [enforce fail at ../third_party/gloo/gloo/transport/tcp/device.cc:127] rp != nullptr. Unable to find address for: 2e3c6f147588

======================================================================
ERROR: test_forward_backward_single_replica (__main__.ReducerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_c10d.py", line 2783, in setUp
    self.process_group = c10d.ProcessGroupGloo(self.store, 0, 1)
RuntimeError: [enforce fail at ../third_party/gloo/gloo/transport/tcp/device.cc:127] rp != nullptr. Unable to find address for: 2e3c6f147588

======================================================================
ERROR: test_forward_backward_unused_parameters (__main__.ReducerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_c10d.py", line 2783, in setUp
    self.process_group = c10d.ProcessGroupGloo(self.store, 0, 1)
RuntimeError: [enforce fail at ../third_party/gloo/gloo/transport/tcp/device.cc:127] rp != nullptr. Unable to find address for: 2e3c6f147588

======================================================================
ERROR: test_multi_dtype_multi_bucket (__main__.ReducerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_c10d.py", line 2783, in setUp
    self.process_group = c10d.ProcessGroupGloo(self.store, 0, 1)
RuntimeError: [enforce fail at ../third_party/gloo/gloo/transport/tcp/device.cc:127] rp != nullptr. Unable to find address for: 2e3c6f147588

======================================================================
ERROR: test_multi_dtype_single_bucket (__main__.ReducerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_c10d.py", line 2783, in setUp
    self.process_group = c10d.ProcessGroupGloo(self.store, 0, 1)
RuntimeError: [enforce fail at ../third_party/gloo/gloo/transport/tcp/device.cc:127] rp != nullptr. Unable to find address for: 2e3c6f147588

======================================================================
ERROR: test_single_dtype_single_bucket (__main__.ReducerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_c10d.py", line 2783, in setUp
    self.process_group = c10d.ProcessGroupGloo(self.store, 0, 1)
RuntimeError: [enforce fail at ../third_party/gloo/gloo/transport/tcp/device.cc:127] rp != nullptr. Unable to find address for: 2e3c6f147588

======================================================================
ERROR: test_default_store_timeout_gloo (__main__.TimeoutTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/nix-build-python3.6-pytorch-1.2.0.drv-0/source/test/common_utils.py", line 917, in wrapper
    return func(*args, **kwargs)
  File "test_c10d.py", line 622, in test_default_store_timeout_gloo
    self._test_default_store_timeout('gloo')
  File "test_c10d.py", line 610, in _test_default_store_timeout
    raise c2p[0]
  File "test_c10d.py", line 575, in _test_store_timeout
    timeout=timedelta(seconds=1))
  File "/nix/store/fagqbi13xgj8353h7wmcj263khn6jj3y-python3.6-pytorch-1.2.0/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 416, in init_process_group
    timeout=timeout)
  File "/nix/store/fagqbi13xgj8353h7wmcj263khn6jj3y-python3.6-pytorch-1.2.0/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 484, in _new_process_group_helper
    timeout=timeout)
RuntimeError: [enforce fail at ../third_party/gloo/gloo/transport/tcp/device.cc:127] rp != nullptr. Unable to find address for: 2e3c6f147588

======================================================================
FAIL: test_ignored_output (__main__.DistributedDataParallelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_c10d.py", line 501, in wrapper
    self._join_processes(fn)
  File "test_c10d.py", line 548, in _join_processes
    self._check_return_codes(elapsed_time)
  File "test_c10d.py", line 563, in _check_return_codes
    self.assertEqual(first_process.exitcode, 0)
  File "/tmp/nix-build-python3.6-pytorch-1.2.0.drv-0/source/test/common_utils.py", line 650, in assertEqual
    super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
AssertionError: 11 not less than or equal to 1e-05 :

======================================================================
FAIL: test_ignored_output_with_unused_parameters (__main__.DistributedDataParallelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_c10d.py", line 501, in wrapper
    self._join_processes(fn)
  File "test_c10d.py", line 548, in _join_processes
    self._check_return_codes(elapsed_time)
  File "test_c10d.py", line 563, in _check_return_codes
    self.assertEqual(first_process.exitcode, 0)
  File "/tmp/nix-build-python3.6-pytorch-1.2.0.drv-0/source/test/common_utils.py", line 650, in assertEqual
    super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
AssertionError: 11 not less than or equal to 1e-05 :

======================================================================
FAIL: test_sparse_gradients (__main__.DistributedDataParallelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_c10d.py", line 501, in wrapper
    self._join_processes(fn)
  File "test_c10d.py", line 548, in _join_processes
    self._check_return_codes(elapsed_time)
  File "test_c10d.py", line 563, in _check_return_codes
    self.assertEqual(first_process.exitcode, 0)
  File "/tmp/nix-build-python3.6-pytorch-1.2.0.drv-0/source/test/common_utils.py", line 650, in assertEqual
    super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
AssertionError: 11 not less than or equal to 1e-05 :

======================================================================
FAIL: test_barrier_implies_wait (__main__.ProcessGroupGlooTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_c10d.py", line 501, in wrapper
    self._join_processes(fn)
  File "test_c10d.py", line 548, in _join_processes
    self._check_return_codes(elapsed_time)
  File "test_c10d.py", line 563, in _check_return_codes
    self.assertEqual(first_process.exitcode, 0)
  File "/tmp/nix-build-python3.6-pytorch-1.2.0.drv-0/source/test/common_utils.py", line 650, in assertEqual
    super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
AssertionError: 7 not less than or equal to 1e-05 :

======================================================================
FAIL: test_timeout_kwarg (__main__.ProcessGroupGlooTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_c10d.py", line 501, in wrapper
    self._join_processes(fn)
  File "test_c10d.py", line 548, in _join_processes
    self._check_return_codes(elapsed_time)
  File "test_c10d.py", line 563, in _check_return_codes
    self.assertEqual(first_process.exitcode, 0)
  File "/tmp/nix-build-python3.6-pytorch-1.2.0.drv-0/source/test/common_utils.py", line 650, in assertEqual
    super(TestCase, self).assertLessEqual(abs(x - y), prec, message)
AssertionError: 7 not less than or equal to 1e-05 :

----------------------------------------------------------------------
Ran 100 tests in 9.528s

FAILED (failures=5, errors=8, skipped=47)
Traceback (most recent call last):
  File "test/run_test.py", line 408, in <module>
    main()
  File "test/run_test.py", line 400, in main
    raise RuntimeError(message)
RuntimeError: test_c10d failed!
builder for '/nix/store/s4jg1wg8vq6rkjx7y53w7r4qnpwvnk2y-python3.6-pytorch-1.2.0.drv' failed with exit code 1
```
I'll try to run it on bare metal next, without docker.
Cheers,
Torsten

**Comment by tscholak** [comment]
a bit of googling revealed this potentially relevant commit: https://github.com/pytorch/pytorch/commit/e316b7d54851fec6c6ae0a669a2e1f644f1d4063
